title: Kamini Manwal # your name (or website title) here
logo: "unnamed.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with a background in teaching & sales. Currently looking for job opportunities that offer excitement and challenging tasks as a data analyst.




 projects.
    
  <br><br>
  <a href="https://www.linkedin.com/in/kaminimanwal/">LinkedIn Profile</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/kamini.manwal/vizzes">Tableau Profile</a>
  <br>
  <a href="C:\Users\Jatin\Desktop\resume_Kamini.pdf"</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
