title: Kamini Manwal # your name (or website title) here
logo: "unnamed.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with experience in data cleaning and analyzing in SQL, Python and Excel.
  
  # <br><br>This portfolio showcases my projects, skills, and dedication to leveraging data to make informed decisions and solve real-world challenges.
  <br><br>
  <a href="https://www.linkedin.com/in/kaminimanwal/">LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/KaminiManwal">GitHub Repo</a> 
  <br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
