title: Kamini Manwal # your name (or website title) here
logo: "unnamed.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 As a certified data analyst from CareeerFoundry,I became experienced in data cleaning and analyzing in Excel, SQL, and Python. I specialize in extracting actionable insights from complex datasets, visualizing data for effective communication, and driving data-informed decision-making.
  <a href="https://www.linkedin.com/in/kaminimanwal/">View My LinkedIn Profile</a> 
  
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
